#' Calculate distance along group's average azimuth
#'
#' Given a group of individuals, calculate average azimuth. Shift the coordinate
#' system to a new origin at the group centroid. Rotate the coordinate system
#' by the average azimuth. Return the distance along the average azimuth as
#' the front-back position in group.
#'
#' @param DT
#' @param az az column name generated by eg. calc_az_sequential, default 'az'
#' @param coords character vector of column names for x, y
#' @param group group column generated by eg. group_pts
#' @param return_rank if rank along average azimuth should also be returned,
#' used by functions calc_az_leader, calc_dist_leader
#' @param ties.method default: 'average', see ?data.table::frank. Note if
#' multiple individuals in a group have identical coordinates, they will
#' receive an average rank (eg. 1.5, 2.5) which may indicate some data cleaning
#' is required.
calc_dist_group_az <- function(DT, az = 'az', coords = c('x', 'y'),
                               group = 'group', return_rank = FALSE,
                               ties.method = 'average') {

  xcol <- first(coords)
  ycol <- last(coords)
  xcol_group <- paste0('group_mean_', xcol)
  ycol_group <- paste0('group_mean_', ycol)

  stopifnot(az %in% colnames(DT))
  stopifnot(group %in% colnames(DT))
  stopifnot(xcol %in% colnames(DT))
  stopifnot(ycol %in% colnames(DT))
  stopifnot(xcol_group %in% colnames(DT))
  stopifnot(ycol_group %in% colnames(DT))

  group_az_col <- 'group_az'
  DT[, c(group_az_col) := mean(.SD[[1]]), by = c(group), .SDcols = c(az)]

  DT[, dist_along_group_az :=
       cos(.SD[[group_az_col]]) * (.SD[[xcol]] - .SD[[xcol_group]]) +
       sin(.SD[[group_az_col]]) * (.SD[[ycol]] - .SD[[ycol_group]]),
     by = .I]

  if (return_rank) {
    DT[, N_by_group := .N, by = c(group)]
    DT[, rank_dist_along_group_az :=
         data.table::frank(-dist_along_group_az, ties.method = ties.method),
       by = c(group)]
  }

  return(DT)
}
