#' Position along group's average bearing as leadership order
#'
#' Given the average bearing of a group of animals, shifts the coordinate
#' system to a new origin at the group centroid and rotates the coordinate system
#' by the average bearing. Returns the distance along the average bearing as
#' the front-back position in group.
#'
#' @param DT
#' @param bearing bearing column name generated by eg. bearing_sequential,
#' default 'bearing'
#' @param coords character vector of column names for x, y
#' @param group group column generated by eg. group_pts
#' @param return_rank if rank along average bearing should also be returned,
#' used by functions bearing_to_leader, distance_to_leader
#' @param ties.method default: 'average', see ?data.table::frank. Note if
#' multiple individuals in a group have identical coordinates, they will
#' receive an average rank (eg. 1.5, 2.5) which may indicate some data cleaning
#' is required.
group_leader <- function(DT, bearing = 'bearing', coords = c('x', 'y'),
                               group = 'group', return_rank = FALSE,
                               ties.method = 'average') {

  xcol <- first(coords)
  ycol <- last(coords)
  xcol_group <- paste0('group_mean_', xcol)
  ycol_group <- paste0('group_mean_', ycol)

  stopifnot(bearing %in% colnames(DT))
  stopifnot(group %in% colnames(DT))
  stopifnot(xcol %in% colnames(DT))
  stopifnot(ycol %in% colnames(DT))
  stopifnot(xcol_group %in% colnames(DT))
  stopifnot(ycol_group %in% colnames(DT))

  group_bearing_col <- 'group_bearing'
  DT[, c(group_bearing_col) := mean(.SD[[1]]), by = c(group), .SDcols = c(bearing)]

  DT[, dist_along_group_bearing :=
       cos(.SD[[group_bearing_col]]) * (.SD[[xcol]] - .SD[[xcol_group]]) +
       sin(.SD[[group_bearing_col]]) * (.SD[[ycol]] - .SD[[ycol_group]]),
     by = .I]

  if (return_rank) {
    DT[, N_by_group := .N, by = c(group)]
    DT[, rank_dist_along_group_bearing :=
         data.table::frank(-dist_along_group_bearing, ties.method = ties.method),
       by = c(group)]
  }

  return(DT)
}
