#' Calculate group polarization
#'
#' Polarization of group bearings from 0-1
#'
#' @param DT with az column generated by calc_az_sequential
#' @param group group column name generated by eg. group_pts
calc_polarization <- function(DT,  group = 'group') {
  stopifnot('az' %in% colnames(DT))
  stopifnot('group' %in% colnames(DT))

  # Klamser 2021: polarization = absolute value of the mean heading direction
  # DT[, polarization := abs(mean(az)), by = c(group)]

  DT[, polarization := CircStats::r.test(.SD[[1]])$r.bar, by = c(group),
     .SDcols = c('az')]


  return(DT)
}