#' Calculate group polarization
#'
#' Polarization of group bearings from 0-1
#'
#' @param DT with az column generated by eg. calc_az_sequential
#' @param az az column name, default 'az'
#' @param group group column name generated by eg. group_pts, default 'group'
calc_polarization <- function(DT,  az = 'az', group = 'group') {

  DT[, polarization := CircStats::r.test(.SD[[1]])$r.bar, by = c(group),
     .SDcols = c('az')]

  return(DT)
}