#' Calculate group polarization
#'
#' Polarization of group bearings from 0-1
#'
#' @param DT with az column generated by eg. calc_az_sequential
#' @param az az column name, default 'az'
#' @param group group column name generated by eg. group_pts, default 'group'
#' @param degree boolean, if az is measured in degrees. See ?CircStats::r.test
calc_polarization <- function(DT,  az = 'az', group = 'group', degree = FALSE) {
  stopifnot(az %in% colnames(DT))
  stopifnot(group %in% colnames(DT))

  DT[, polarization := CircStats::r.test(.SD[[1]], degree = degree)$r.bar,
     by = c(group),
     .SDcols = c(az)]

  return(DT)
}