project:
  type: manuscript
  output-dir: public
  execute-dir: project
  render:
    - "!tests"

# manuscript:
  # notebooks:
  #   - notebook: supplement/supplement-b.qmd
  #     title: "Supplement B: Review Results"
  # appendices:
  #   - supplement/supplement-b.qmd

website:
  title: "spatsoc paper 2"
  sidebar:
    contents: auto
    tools:
      - icon: gitlab
        href: https://gitlab.com/robitalec/spatsoc-paper-2

format:
  html:
    theme:
      dark: darkly
      light: flatly
    toc: true
    code-line-numbers: false
    code-copy: true
    code-link: true
    code-block-border-left: false
    comments: false
  docx: default
  jats: default
  # pdf: default      hypothesis: true
      hypothesis: true
    # csl: https://www.zotero.org/styles/methods-in-ecology-and-evolution
