project:
  type: manuscript
  output-dir: public
  execute-dir: project
  render: 
    - "index.qmd"
    - "supplement-a.qmd"
    - "supplement-b.qmd"
    - "supplement-c.qmd"
    - "!title-page.qmd"


format:
  jats: default
  html:
    theme:
      dark: darkly
      light: flatly
    toc: true
    code-line-numbers: false
    code-copy: true
    code-link: true
    code-block-border-left: false
    comments:
      hypothesis: true
  typst:
    include-in-header:
      - text: |
          #set text(hyphenate: false)
          #show figure: set block(breakable: true)
          #set par.line(numbering: "1")
          #set text(top-edge: 0.7em, bottom-edge: -0.3em)
          #set par(leading: 1em, spacing: 2em)