project:
  type: manuscript
  output-dir: public
  execute-dir: project

manuscript:
  notebooks:
    - notebook: notebooks/box-1.qmd
      title: Box 1
    - notebook: notebooks/supplement-a.qmd
      title: "Supplement A: Review Methods"
    - notebook: notebooks/supplement-b.qmd
      title: "Supplement B: Review Results"
    - notebook: notebooks/supplement-c.qmd
      title: "Supplement C: Selected Metrics"

website:
  title: "spatsoc paper 2"
  sidebar:
    contents: auto
    tools:
      - icon: gitlab
        href: https://gitlab.com/robitalec/spatsoc-paper-2

format:
  html:
    theme:
      dark: darkly
      light: flatly
    toc: true
    code-line-numbers: false
    code-copy: true
    code-link: true
    code-block-border-left: false
