# Supplement: Scoping review methods {#sec-scoping-methods}

```{r}
#| include: false
targets::tar_source('R')

tar_load(review)
tar_load(geocoded)
tar_load(taxized)
tar_load(software_meta)

tar_load(counted)
count_code_avail <- counted$count_code_avail
count_prog_lang <- counted$count_prog_lang
count_software <- counted$count_software
count_metric <- counted$count_metric
count_dom_metric <- counted$count_dom_metric
```



::: {#suptbl-benchmark}
```{r}
#| echo: false
targets::tar_read(benchmark_papers) |>
  tinytable::tt() |>
  style_tt(align = 'l') |>
  format_tt(escape = TRUE)
```
Benchmark papers used to evaluate iterative search results for scoping review
:::

::: {#suptbl-search-strings}
```{r}
#| echo: false
targets::tar_read(search_strings) |>
  tinytable::tt() |>
  style_tt(align = 'l') |>
  format_tt(escape = TRUE)
```

Search strings for scoping review using Web of Science and Scopus
:::

::: {#suptbl-form}
```{r}
#| echo: false
data.table::fread('data/form.csv') |>
  tinytable::tt() |>
  style_tt(align = 'l') |>
  format_tt(escape = TRUE)
```
Data extraction form for scoping review to identify metrics for studying intragroup dynamics
:::