---
title: "Discussion"
date: "`r Sys.Date()`"
toc: true
execute:
  echo: false
---

```{r}
#| include: false
targets::tar_source('R')
```


- social networks, history of spatsoc
- high number of studies with IID, NND


Animal social dynamics have broad implications in ecology including resource
availability, disease transmission and collective behaviour. Social network
analysis can measure the structure of social systems, the consequences of an
individual's position in a network, the spread of disease or information across
networks, and the influence of the environment (Farine and Whitehead 2015). Open
source tools have been developed to derive social networks from animal telemetry
data (Robitaille et al 2019) using aggregated association rates or home range
overlap. The methods have been used to measure contact rates to measure social
cohesion (Bracken 2021), human-wildlife conflict (Boudreau 2021), socioecology
and resource availability (Peignier2019),  community structure (Sunga 2021),
influence of stress of social proximity (Keshavarzi 2023), social patterns in
non-social species (Heeres 2024).

